// External Imports
import "package:flutter/material.dart";
import "package:frankenstein/features/character_creation/tabs/asi_feat_tab.dart" show AsiFeatTab;
import "package:frankenstein/features/character_creation/tabs/class_tab.dart" show ClassTab;
import "package:frankenstein/features/character_creation/tabs/equipment_tab.dart" show EquipmentTab;
import "package:frankenstein/features/character_creation/tabs/spells_tab.dart" show SpellsTab;
import "package:frankenstein/storage/global_list_manager.dart" show GlobalListManager;

// Project Imports
import "../../../models/character/character.dart";
import "../../../theme/theme_manager.dart";
import "../../../utils/style_utils.dart";
import "../tabs/ability_score_tab.dart" show AbilityScoreTab;
import "../tabs/background_tab.dart" show BackgroundTab;
import "../tabs/backstory_tab.dart" show BackstoryTab;
import "../tabs/basics_tab.dart" show BasicsTab;
import "../tabs/finishing_up_tab.dart" show FinishingUpTab;
import "../tabs/race_tab.dart" show RaceTab;

/* Notifier for when settings changes colour to rebuild. */
final ValueNotifier<int> tabRebuildNotifier = ValueNotifier<int>(0);

class CreateACharacter extends StatefulWidget {
  const CreateACharacter({super.key});

  @override
  MainCreateCharacter createState() => MainCreateCharacter();
}

class MainCreateCharacter extends State<CreateACharacter>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  late Character character;
  late Future<void> _initialisedContent;
  @override
  void initState() {
    super.initState();
    ThemeManager.instance.addListener(_onThemeChanged);
    _initialisedContent = initialiseContent();
  }


  Future<void> initialiseContent() async {
    await GlobalListManager().initialiseContentLists(); // Optimise out necessary loads
    character = Character.createDefault();
  }
  
  @override
  void dispose() {
    ThemeManager.instance.removeListener(_onThemeChanged);
    super.dispose();
  }
  
  void _onThemeChanged() {
    setState(() {
      // Rebuild when theme changes
    });
  }

  // Text editing controllers
  /// Basics 
  TextEditingController nameEnterController = TextEditingController();
  TextEditingController playerNameEnterController = TextEditingController();
  TextEditingController genderEnterController = TextEditingController();
  /// Character group
  TextEditingController groupEnterController = TextEditingController();
  
  static const List<String> tabLabels = [
    "Basics",
    "Race",
    "Class",
    "Background",
    "Ability Scores",
    "ASIs and Feats",
    "Spells",
    "Equipment",
    "Backstory",
    "Finishing up"
  ];

  static const List<String> abilityScores = [
    "Strength",
    "Dexterity",
    "Constitution",
    "Intelligence",
    "Wisdom",
    "Charisma"
  ];

  
  // Stores the widgets generated by class levels
  List<Widget> widgetsInPlay = []; 
  String? levellingMethod;
  String? characterLevel = "1";
  int pointsRemaining = 27;
  List<String> coinTypesSelected = ["Gold"];
  // TODO: Moved featFilters and filteredFeats to AsiFeatTab where they're actually used

  int numberOfRemainingFeatOrASIs = 0;
  bool remainingAsi = false;
  

  // FUTUREPLAN(Implement an experience levelling alternative using these)
  String enteredExperience = "";
  TextEditingController experienceEnterController = TextEditingController();
  
  // FUTUREPLAN(Implement a better skill proficiency section using skillProficienciesMap and adding a second field then delete this)
  List<String> skillProficiencies = [];

  int get charLevel {
    return int.parse(characterLevel ?? "1");
  }

  bool get canCreateCharacter {
    return (pointsRemaining == 0 &&
      numberOfRemainingFeatOrASIs == 0 &&
      !remainingAsi &&
      charLevel <= character.classList.length &&
      character.chosenAllEqipment && 
      character.chosenAllSpells
    );
  }

  @override
  Widget build(
    BuildContext context,
  ) {
    super.build(context);

    return StyleUtils.styledFutureBuilder(future: _initialisedContent, builder: (context) => ValueListenableBuilder<int>(
      valueListenable: tabRebuildNotifier,
      builder: (context, value, child) {return DefaultTabController(
      length: tabLabels.length,
      child: Scaffold(
        backgroundColor: ThemeManager.instance.currentScheme.backgroundColour,
        appBar: StyleUtils.buildStyledAppBar(
          title: "Create a character",
          titleStyle: TextStyle(
            fontSize: 40, 
            fontWeight: FontWeight.w700,
            color: ThemeManager.instance.currentScheme.textColour,
          ),
          bottom: TabBar(
            tabs: tabLabels.map((e) => StyleUtils.tabLabel(e)).toList(),
            indicatorColor: ThemeManager.instance.currentScheme.textColour,
          ),
        ),
        body: TabBarView(children: [
          // Basics Tab
          BasicsTab(
            character: character,
            levellingMethod: levellingMethod,
            characterLevel: characterLevel,
            nameEnterController: nameEnterController,
            playerNameEnterController: playerNameEnterController,
            genderEnterController: genderEnterController,
            experienceEnterController: experienceEnterController,
            numberOfRemainingFeatOrASIs: numberOfRemainingFeatOrASIs,
            onCharacterChanged: () {
              setState(() {});
            },
            onLevellingMethodChanged: (newMethod) {
              setState(() {
                levellingMethod = newMethod;
              });
            },
            onCharacterLevelChanged: (newLevel) {
              setState(() {
                characterLevel = newLevel;
              });
            },
            onNumberOfRemainingFeatOrASIsChanged: (newCount) {
              setState(() {
                numberOfRemainingFeatOrASIs = newCount;
              });
            },
          ),
          
          // Race Tab
          RaceTab(
            character: character,
            onCharacterChanged: () {
              setState(() {});
            },
          ),

          // Class Tab
          ClassTab(
            character: character,
            charLevel: charLevel,
            characterLevel: characterLevel,
            widgetsInPlay: widgetsInPlay,
            numberOfRemainingFeatOrASIs: numberOfRemainingFeatOrASIs,
            tabRebuildNotifier: tabRebuildNotifier,
            onCharacterChanged: () {
              setState(() {});
            },
            onCharacterLevelChanged: (newLevel) {
              setState(() {
                characterLevel = newLevel;
              });
            },
            onWidgetsInPlayChanged: (newWidgets) {
              setState(() {
                widgetsInPlay = newWidgets;
              });
            },
            onNumberOfRemainingFeatOrASIsChanged: (newCount) {
              setState(() {
                numberOfRemainingFeatOrASIs = newCount;
              });
            },
          ),
          
          // Background Tab
          BackgroundTab(
            character: character,
            onCharacterChanged: () {
              setState(() {});
            },
          ),
          
          // Ability Score Tab
          AbilityScoreTab(
            character: character,
            pointsRemaining: pointsRemaining,
            onPointsRemainingChanged: (newPoints) {
              setState(() {
                pointsRemaining = newPoints;
              });
            },
          ),
                    
          // Ability Score Improvement & Feat selection tab
          AsiFeatTab(
            character: character,
            numberOfRemainingFeatOrASIs: numberOfRemainingFeatOrASIs,
            remainingAsi: remainingAsi,
            widgetsInPlay: widgetsInPlay,
            onCharacterChanged: () {
              setState(() {});
            },
            onRemainingFeatOrASIsChanged: (newCount) {
              setState(() {
                numberOfRemainingFeatOrASIs = newCount;
              });
            },
            onRemainingAsiChanged: (newValue) {
              setState(() {
                remainingAsi = newValue;
              });
            },
            onWidgetsInPlayChanged: (newWidgets) {
              setState(() {
                widgetsInPlay = newWidgets;
              });
            },
          ),

          // Spells Tab
          SpellsTab(
            character: character,
            onCharacterChanged: () {
              setState(() {});
            },
          ),
          
          // Equipment Tab
          EquipmentTab(
            character: character,
            coinTypesSelected: coinTypesSelected,
            onCharacterChanged: () {
              setState(() {});
            },
            onCoinTypesChanged: (newCoinTypes) {
              setState(() {
                coinTypesSelected = newCoinTypes;
              });
            },
          ),
          
          // Backstory Tab
          BackstoryTab(
            character: character,
            onCharacterChanged: () {
              setState(() {
                // This will trigger a rebuild if other tabs need to reflect backstory changes
              });
              // DO NOTHING AS BACKSTORY CHANGES DO NOT AFFECT OTHER TABS
            },
          ),
          
          // Finishing Up Tab
          FinishingUpTab(
            character: character,
            groupEnterController: groupEnterController,
            canCreateCharacter: canCreateCharacter,
            pointsRemaining: pointsRemaining,
            numberOfRemainingFeatOrASIs: numberOfRemainingFeatOrASIs,
            remainingAsi: remainingAsi,
            charLevel: charLevel,
            onCharacterChanged: () {
              setState(() {});
            },
            congratulationsTitle: 'Character Created!',
          ),
        ]),
      ),
    );}));
  }
}
